include current-theme.conf

# Enable remote control for dynamic transparency
allow_remote_control yes
listen_on unix:/tmp/kitty

# Remove padding and align content to top-left to avoid extra lines
window_padding_width 0 0 12 0
placement_strategy top-left
resize_in_steps yes
