[icloud]
type = webdav
url = https://p01-drivews.icloud.com
vendor = other
user = graeme.sullivan@live.com
pass = 7PZyBH0ZnjyJVjIjbUQ8xND9KTeZ-EYcZd0A7gBVNmleqcI

[gdrive]
token = {"access_token":"ya29.a0ATkoCc4QVUTBxT3dmyKzeFBnu-1r8RmRFZlLUuzMVG0CzoI9swSiUsjCz0Z7-yiRP5f554Im0zVerqSWIl4EVYs2eDrx-DDUqtPevdxAhyDD3SWfV340oBXIgwxQ-f3y8BkTNvDB6uLe4gkaGj8FBN28DNJfYh75IZypmBdndmU3RyUvMUfPa_PonuPUZ1KiDQvZPOLJgQaCgYKARsSARUSFQHGX2MiLFDT7E7YPC4iqRZn0BEevw0209","token_type":"Bearer","refresh_token":"1//0gVYX-vz1aav_CgYIARAAGBASNwF-L9IrkdVQ2CsCAxqn9C_y69aWVhHbfTOVN9o7cB1ax9o6nm5AezXMlbbHEYtrWVJlY4lcmio","expiry":"2026-03-10T15:50:04.851786447+13:00","expires_in":3599}

[googledrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc7LzzNnTe67xPOSYf7a1ZRbz20VlybSTe_9ZmUMNrxLE7N3kOLTh8EfO8cWI7hPQDC5Mi08011epoClwj05NWrn3a6C-JEdgO-xWAKFobHJydRSdF5nKoZz_ybE4uRqIhNg_2ZqV3Z-G5BqicySJYiy2B1PM9buswMboNJWtnXkrkHCJeLvYBmwABuawa3qKBsaCgYKAQESARUSFQHGX2MiFFo2FdBjStIec2Y-YiXmfA0206","token_type":"Bearer","refresh_token":"1//0gQ71HtKJs0C9CgYIARAAGBASNwF-L9Irwmk8tzxrGx0wWlpqXsHRUWNmh3PKgt0Qq8R6lTQ3EFLFEJeQ3SfuDMw3E70RrRUj4dQ","expiry":"2026-03-11T03:18:53.112341957+13:00","expires_in":3599}
team_drive = 

[g drive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7MYirxcLRhRnw-OnCQC_JHnMG4qNy02gRRjUSGoylAyXUP6iR_Ny9jFaj9ARlvAJO1wuZUMEnsPwIck9rDZ3CdAm-rigS-7DzVQW6dRAohkTOtRUHbyDhXRTTQgatcC0w7XcfBVntqvSbNv1egt7dQmQcas1A68O3BgJgMoxqfn5RhlYkJ_OsGNgpROcI046kYXJAkaCgYKAYsSARUSFQHGX2MimwE5FmK10bA1339GZfci9w0207","token_type":"Bearer","refresh_token":"1//0gcdD_VVbW0R2CgYIARAAGBASNwF-L9Ir3D69KsEEgOzDVR6kdDvWMgIS-qeTK_dpMZzFlO2pfNM76BZRkqPAAWMQJpF8-EZXfKE","expiry":"2026-03-27T11:32:26.373524126+13:00","expires_in":3599}
team_drive = 

